name: Trigger Auto-Cancel Function
on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Function
        run: |
          curl -X POST https://awpczipxzeurlpmmrzid.supabase.co/functions/v1/auto-cancel-shifts \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{}'
